version: "3.8"

services:
  room-app:
    build: .
    image: goshtaspm/roomapp:latest
    container_name: room-app
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://room-db:3306/roomdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - room-db
    networks:
      - room-network

  room-db:
    image: mariadb:11.4
    container_name: room-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: roomdb
    ports:
      - "3306:3306"
    networks:
      - room-network

networks:
  room-network:
    driver: bridge
